packages:
  - products/*
  - docs
  - setup

catalog:
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  prettier: ^3.6.2
  typescript: 5.9.2
  vitest: ^3.2.4

catalogs:
  backend:
    '@cloudflare/workers-types': ^4.20250921.0
    '@types/pg': ^8.15.5
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    hono: ^4.9.8
    pg: ^8.16.3
    wrangler: ^4.38.0
  docs:
    '@astrojs/check': ^0.9.4
    astro: ^5.13.9
    prettier-plugin-astro: ^0.14.1
  frontend:
    '@eslint/js': ^9.36.0
    '@sentry/react': ^10.12.0
    '@sentry/vite-plugin': ^4.3.0
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    '@vitejs/plugin-react-swc': ^4.1.0
    eslint: ^9.36.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    globals: ^16.4.0
    happy-dom: ^18.0.1
    react: ^19.1.1
    react-dom: ^19.1.1
    react-router: ^7.9.1
    typescript-eslint: ^8.44.0
    vite: ^7.1.6
  root:
    turbo: ^2.5.6
  setup:
    dotenv: ^17.2.2
    tsx: ^4.20.5

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
