packages:
  - products/*
  - docs
  - setup

catalog:
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  prettier: 3.6.2
  typescript: 5.9.2
  vitest: ^3.2.4
  zod: ^4.1.12

catalogs:
  backend:
    '@cloudflare/workers-types': ^4.20251008.0
    '@hono/zod-openapi': ^1.1.3
    '@scalar/hono-api-reference': ^0.9.20
    '@types/pg': ^8.15.5
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
    hono: ^4.9.10
    pg: ^8.16.3
    wrangler: ^4.42.1
    zod-openapi-share: ^0.0.4
  docs:
    '@astrojs/check': ^0.9.4
    astro: ^5.14.1
    prettier-plugin-astro: ^0.14.1
  frontend:
    '@eslint/js': ^9.37.0
    '@faker-js/faker': ^10.0.0
    '@hookform/error-message': ^2.0.1
    '@hookform/resolvers': ^5.2.2
    '@sentry/react': ^10.18.0
    '@sentry/vite-plugin': ^4.3.0
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.1
    '@vitejs/plugin-react-swc': ^4.1.0
    eslint: ^9.37.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.23
    globals: ^16.4.0
    happy-dom: ^18.0.1
    msw: ^2.11.3
    orval: ^7.13.2
    react: ^19.2.0
    react-dom: ^19.2.0
    react-hook-form: ^7.64.0
    react-router: ^7.9.3
    swr: ^2.3.6
    typescript-eslint: ^8.46.0
    vite: ^7.1.9
  node:
    tsx: ^4.20.6
  root:
    turbo: ^2.5.8
  setup:
    dotenv: ^17.2.3
    dotenv-caster: ^2.1.23

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
