name: Test Request
description: This template is a issue for requesting new tests.
title: 'Test Request'

body:
  - type: markdown
    id: body
    attributes:
      value: |
        ## Test Request
        Please provide a clear and concise description of the test you would like to add.
  - type: input
    id: title
    attributes:
      label: Title
      description: A short summary of the test.
      placeholder: A short summary of the test.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the test.
      placeholder: A detailed description of the test.
