/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Echo API
 * 受け取った入力値をそのまま応答するAPI
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { GetApiUsers200Item, GetApiUsers500, PostApiUsers201Item, PostApiUsers500 } from './api.schemas';

export const getGetApiUsersResponseMock = (): GetApiUsers200Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    email: faker.internet.email(),
    password: faker.string.alpha({ length: { min: 6, max: 20 } }),
  }));

export const getGetApiUsersResponseMock200 = (): GetApiUsers200Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    email: faker.internet.email(),
    password: faker.string.alpha({ length: { min: 6, max: 20 } }),
  }));

export const getGetApiUsersResponseMock500 = (overrideResponse: Partial<GetApiUsers500> = {}): GetApiUsers500 => ({
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement([100] as const),
    faker.helpers.arrayElement([102] as const),
    faker.helpers.arrayElement([103] as const),
    faker.helpers.arrayElement([200] as const),
    faker.helpers.arrayElement([201] as const),
    faker.helpers.arrayElement([202] as const),
    faker.helpers.arrayElement([203] as const),
    faker.helpers.arrayElement([206] as const),
    faker.helpers.arrayElement([207] as const),
    faker.helpers.arrayElement([208] as const),
    faker.helpers.arrayElement([226] as const),
    faker.helpers.arrayElement([300] as const),
    faker.helpers.arrayElement([301] as const),
    faker.helpers.arrayElement([302] as const),
    faker.helpers.arrayElement([303] as const),
    faker.helpers.arrayElement([305] as const),
    faker.helpers.arrayElement([306] as const),
    faker.helpers.arrayElement([307] as const),
    faker.helpers.arrayElement([308] as const),
    faker.helpers.arrayElement([400] as const),
    faker.helpers.arrayElement([401] as const),
    faker.helpers.arrayElement([402] as const),
    faker.helpers.arrayElement([403] as const),
    faker.helpers.arrayElement([404] as const),
    faker.helpers.arrayElement([405] as const),
    faker.helpers.arrayElement([406] as const),
    faker.helpers.arrayElement([407] as const),
    faker.helpers.arrayElement([408] as const),
    faker.helpers.arrayElement([409] as const),
    faker.helpers.arrayElement([410] as const),
    faker.helpers.arrayElement([411] as const),
    faker.helpers.arrayElement([412] as const),
    faker.helpers.arrayElement([413] as const),
    faker.helpers.arrayElement([414] as const),
    faker.helpers.arrayElement([415] as const),
    faker.helpers.arrayElement([416] as const),
    faker.helpers.arrayElement([417] as const),
    faker.helpers.arrayElement([418] as const),
    faker.helpers.arrayElement([421] as const),
    faker.helpers.arrayElement([422] as const),
    faker.helpers.arrayElement([423] as const),
    faker.helpers.arrayElement([424] as const),
    faker.helpers.arrayElement([425] as const),
    faker.helpers.arrayElement([426] as const),
    faker.helpers.arrayElement([428] as const),
    faker.helpers.arrayElement([429] as const),
    faker.helpers.arrayElement([431] as const),
    faker.helpers.arrayElement([451] as const),
    faker.helpers.arrayElement([500] as const),
    faker.helpers.arrayElement([501] as const),
    faker.helpers.arrayElement([502] as const),
    faker.helpers.arrayElement([503] as const),
    faker.helpers.arrayElement([504] as const),
    faker.helpers.arrayElement([505] as const),
    faker.helpers.arrayElement([506] as const),
    faker.helpers.arrayElement([507] as const),
    faker.helpers.arrayElement([508] as const),
    faker.helpers.arrayElement([510] as const),
    faker.helpers.arrayElement([511] as const),
    faker.helpers.arrayElement([-1] as const),
  ]),
  message: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getPostApiUsersResponseMock = (): PostApiUsers201Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    email: faker.internet.email(),
    password: faker.string.alpha({ length: { min: 6, max: 20 } }),
  }));

export const getPostApiUsersResponseMock201 = (): PostApiUsers201Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    email: faker.internet.email(),
    password: faker.string.alpha({ length: { min: 6, max: 20 } }),
  }));

export const getPostApiUsersResponseMock500 = (overrideResponse: Partial<PostApiUsers500> = {}): PostApiUsers500 => ({
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement([100] as const),
    faker.helpers.arrayElement([102] as const),
    faker.helpers.arrayElement([103] as const),
    faker.helpers.arrayElement([200] as const),
    faker.helpers.arrayElement([201] as const),
    faker.helpers.arrayElement([202] as const),
    faker.helpers.arrayElement([203] as const),
    faker.helpers.arrayElement([206] as const),
    faker.helpers.arrayElement([207] as const),
    faker.helpers.arrayElement([208] as const),
    faker.helpers.arrayElement([226] as const),
    faker.helpers.arrayElement([300] as const),
    faker.helpers.arrayElement([301] as const),
    faker.helpers.arrayElement([302] as const),
    faker.helpers.arrayElement([303] as const),
    faker.helpers.arrayElement([305] as const),
    faker.helpers.arrayElement([306] as const),
    faker.helpers.arrayElement([307] as const),
    faker.helpers.arrayElement([308] as const),
    faker.helpers.arrayElement([400] as const),
    faker.helpers.arrayElement([401] as const),
    faker.helpers.arrayElement([402] as const),
    faker.helpers.arrayElement([403] as const),
    faker.helpers.arrayElement([404] as const),
    faker.helpers.arrayElement([405] as const),
    faker.helpers.arrayElement([406] as const),
    faker.helpers.arrayElement([407] as const),
    faker.helpers.arrayElement([408] as const),
    faker.helpers.arrayElement([409] as const),
    faker.helpers.arrayElement([410] as const),
    faker.helpers.arrayElement([411] as const),
    faker.helpers.arrayElement([412] as const),
    faker.helpers.arrayElement([413] as const),
    faker.helpers.arrayElement([414] as const),
    faker.helpers.arrayElement([415] as const),
    faker.helpers.arrayElement([416] as const),
    faker.helpers.arrayElement([417] as const),
    faker.helpers.arrayElement([418] as const),
    faker.helpers.arrayElement([421] as const),
    faker.helpers.arrayElement([422] as const),
    faker.helpers.arrayElement([423] as const),
    faker.helpers.arrayElement([424] as const),
    faker.helpers.arrayElement([425] as const),
    faker.helpers.arrayElement([426] as const),
    faker.helpers.arrayElement([428] as const),
    faker.helpers.arrayElement([429] as const),
    faker.helpers.arrayElement([431] as const),
    faker.helpers.arrayElement([451] as const),
    faker.helpers.arrayElement([500] as const),
    faker.helpers.arrayElement([501] as const),
    faker.helpers.arrayElement([502] as const),
    faker.helpers.arrayElement([503] as const),
    faker.helpers.arrayElement([504] as const),
    faker.helpers.arrayElement([505] as const),
    faker.helpers.arrayElement([506] as const),
    faker.helpers.arrayElement([507] as const),
    faker.helpers.arrayElement([508] as const),
    faker.helpers.arrayElement([510] as const),
    faker.helpers.arrayElement([511] as const),
    faker.helpers.arrayElement([-1] as const),
  ]),
  message: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getGetApiUsersMockHandler = (
  overrideResponse?:
    | GetApiUsers200Item[]
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiUsers200Item[]> | GetApiUsers200Item[]),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiUsersResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getGetApiUsersMockHandler200 = (
  overrideResponse?:
    | GetApiUsers200Item[]
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiUsers200Item[]> | GetApiUsers200Item[]),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiUsersResponseMock200()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getGetApiUsersMockHandler500 = (
  overrideResponse?:
    | GetApiUsers500
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiUsers500> | GetApiUsers500),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiUsersResponseMock500()
        ),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiUsersMockHandler = (
  overrideResponse?:
    | PostApiUsers201Item[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0]
      ) => Promise<PostApiUsers201Item[]> | PostApiUsers201Item[]),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiUsersResponseMock()
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiUsersMockHandler201 = (
  overrideResponse?:
    | PostApiUsers201Item[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0]
      ) => Promise<PostApiUsers201Item[]> | PostApiUsers201Item[]),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiUsersResponseMock201()
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiUsersMockHandler500 = (
  overrideResponse?:
    | PostApiUsers500
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiUsers500> | PostApiUsers500),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/users',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiUsersResponseMock500()
        ),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};
export const getEchoAPIMock = () => [getGetApiUsersMockHandler(), getPostApiUsersMockHandler()];
