/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Echo API
 * 受け取った入力値をそのまま応答するAPI
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  DeleteApiHistory200,
  DeleteApiHistory500,
  GetApiHistory200Item,
  GetApiHistory500,
  PostApiHistory201,
  PostApiHistory500,
} from './api.schemas';

export const getGetApiHistoryResponseMock = (): GetApiHistory200Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    from: faker.string.alpha({ length: { min: 1, max: 20 } }),
    to: faker.string.alpha({ length: { min: 1, max: 20 } }),
    amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
  }));

export const getGetApiHistoryResponseMock200 = (): GetApiHistory200Item[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    from: faker.string.alpha({ length: { min: 1, max: 20 } }),
    to: faker.string.alpha({ length: { min: 1, max: 20 } }),
    amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
  }));

export const getGetApiHistoryResponseMock500 = (
  overrideResponse: Partial<GetApiHistory500> = {}
): GetApiHistory500 => ({
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement([100] as const),
    faker.helpers.arrayElement([102] as const),
    faker.helpers.arrayElement([103] as const),
    faker.helpers.arrayElement([200] as const),
    faker.helpers.arrayElement([201] as const),
    faker.helpers.arrayElement([202] as const),
    faker.helpers.arrayElement([203] as const),
    faker.helpers.arrayElement([206] as const),
    faker.helpers.arrayElement([207] as const),
    faker.helpers.arrayElement([208] as const),
    faker.helpers.arrayElement([226] as const),
    faker.helpers.arrayElement([300] as const),
    faker.helpers.arrayElement([301] as const),
    faker.helpers.arrayElement([302] as const),
    faker.helpers.arrayElement([303] as const),
    faker.helpers.arrayElement([305] as const),
    faker.helpers.arrayElement([306] as const),
    faker.helpers.arrayElement([307] as const),
    faker.helpers.arrayElement([308] as const),
    faker.helpers.arrayElement([400] as const),
    faker.helpers.arrayElement([401] as const),
    faker.helpers.arrayElement([402] as const),
    faker.helpers.arrayElement([403] as const),
    faker.helpers.arrayElement([404] as const),
    faker.helpers.arrayElement([405] as const),
    faker.helpers.arrayElement([406] as const),
    faker.helpers.arrayElement([407] as const),
    faker.helpers.arrayElement([408] as const),
    faker.helpers.arrayElement([409] as const),
    faker.helpers.arrayElement([410] as const),
    faker.helpers.arrayElement([411] as const),
    faker.helpers.arrayElement([412] as const),
    faker.helpers.arrayElement([413] as const),
    faker.helpers.arrayElement([414] as const),
    faker.helpers.arrayElement([415] as const),
    faker.helpers.arrayElement([416] as const),
    faker.helpers.arrayElement([417] as const),
    faker.helpers.arrayElement([418] as const),
    faker.helpers.arrayElement([421] as const),
    faker.helpers.arrayElement([422] as const),
    faker.helpers.arrayElement([423] as const),
    faker.helpers.arrayElement([424] as const),
    faker.helpers.arrayElement([425] as const),
    faker.helpers.arrayElement([426] as const),
    faker.helpers.arrayElement([428] as const),
    faker.helpers.arrayElement([429] as const),
    faker.helpers.arrayElement([431] as const),
    faker.helpers.arrayElement([451] as const),
    faker.helpers.arrayElement([500] as const),
    faker.helpers.arrayElement([501] as const),
    faker.helpers.arrayElement([502] as const),
    faker.helpers.arrayElement([503] as const),
    faker.helpers.arrayElement([504] as const),
    faker.helpers.arrayElement([505] as const),
    faker.helpers.arrayElement([506] as const),
    faker.helpers.arrayElement([507] as const),
    faker.helpers.arrayElement([508] as const),
    faker.helpers.arrayElement([510] as const),
    faker.helpers.arrayElement([511] as const),
    faker.helpers.arrayElement([-1] as const),
  ]),
  message: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getPostApiHistoryResponseMock = (): PostApiHistory201 =>
  faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
      from: faker.string.alpha({ length: { min: 1, max: 20 } }),
      to: faker.string.alpha({ length: { min: 1, max: 20 } }),
      amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    })),
    null,
    null,
  ]);

export const getPostApiHistoryResponseMock201 = (): PostApiHistory201 =>
  faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
      from: faker.string.alpha({ length: { min: 1, max: 20 } }),
      to: faker.string.alpha({ length: { min: 1, max: 20 } }),
      amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    })),
    null,
    null,
  ]);

export const getPostApiHistoryResponseMock500 = (
  overrideResponse: Partial<PostApiHistory500> = {}
): PostApiHistory500 => ({
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement([100] as const),
    faker.helpers.arrayElement([102] as const),
    faker.helpers.arrayElement([103] as const),
    faker.helpers.arrayElement([200] as const),
    faker.helpers.arrayElement([201] as const),
    faker.helpers.arrayElement([202] as const),
    faker.helpers.arrayElement([203] as const),
    faker.helpers.arrayElement([206] as const),
    faker.helpers.arrayElement([207] as const),
    faker.helpers.arrayElement([208] as const),
    faker.helpers.arrayElement([226] as const),
    faker.helpers.arrayElement([300] as const),
    faker.helpers.arrayElement([301] as const),
    faker.helpers.arrayElement([302] as const),
    faker.helpers.arrayElement([303] as const),
    faker.helpers.arrayElement([305] as const),
    faker.helpers.arrayElement([306] as const),
    faker.helpers.arrayElement([307] as const),
    faker.helpers.arrayElement([308] as const),
    faker.helpers.arrayElement([400] as const),
    faker.helpers.arrayElement([401] as const),
    faker.helpers.arrayElement([402] as const),
    faker.helpers.arrayElement([403] as const),
    faker.helpers.arrayElement([404] as const),
    faker.helpers.arrayElement([405] as const),
    faker.helpers.arrayElement([406] as const),
    faker.helpers.arrayElement([407] as const),
    faker.helpers.arrayElement([408] as const),
    faker.helpers.arrayElement([409] as const),
    faker.helpers.arrayElement([410] as const),
    faker.helpers.arrayElement([411] as const),
    faker.helpers.arrayElement([412] as const),
    faker.helpers.arrayElement([413] as const),
    faker.helpers.arrayElement([414] as const),
    faker.helpers.arrayElement([415] as const),
    faker.helpers.arrayElement([416] as const),
    faker.helpers.arrayElement([417] as const),
    faker.helpers.arrayElement([418] as const),
    faker.helpers.arrayElement([421] as const),
    faker.helpers.arrayElement([422] as const),
    faker.helpers.arrayElement([423] as const),
    faker.helpers.arrayElement([424] as const),
    faker.helpers.arrayElement([425] as const),
    faker.helpers.arrayElement([426] as const),
    faker.helpers.arrayElement([428] as const),
    faker.helpers.arrayElement([429] as const),
    faker.helpers.arrayElement([431] as const),
    faker.helpers.arrayElement([451] as const),
    faker.helpers.arrayElement([500] as const),
    faker.helpers.arrayElement([501] as const),
    faker.helpers.arrayElement([502] as const),
    faker.helpers.arrayElement([503] as const),
    faker.helpers.arrayElement([504] as const),
    faker.helpers.arrayElement([505] as const),
    faker.helpers.arrayElement([506] as const),
    faker.helpers.arrayElement([507] as const),
    faker.helpers.arrayElement([508] as const),
    faker.helpers.arrayElement([510] as const),
    faker.helpers.arrayElement([511] as const),
    faker.helpers.arrayElement([-1] as const),
  ]),
  message: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getDeleteApiHistoryResponseMock = (): DeleteApiHistory200 =>
  faker.helpers.arrayElement([
    {
      id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
      from: faker.string.alpha({ length: { min: 1, max: 20 } }),
      to: faker.string.alpha({ length: { min: 1, max: 20 } }),
      amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    },
    null,
    null,
  ]);

export const getDeleteApiHistoryResponseMock200 = (): DeleteApiHistory200 =>
  faker.helpers.arrayElement([
    {
      id: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
      from: faker.string.alpha({ length: { min: 1, max: 20 } }),
      to: faker.string.alpha({ length: { min: 1, max: 20 } }),
      amount: faker.number.float({ min: 1, max: undefined, fractionDigits: 2 }),
    },
    null,
    null,
  ]);

export const getDeleteApiHistoryResponseMock500 = (
  overrideResponse: Partial<DeleteApiHistory500> = {}
): DeleteApiHistory500 => ({
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement([100] as const),
    faker.helpers.arrayElement([102] as const),
    faker.helpers.arrayElement([103] as const),
    faker.helpers.arrayElement([200] as const),
    faker.helpers.arrayElement([201] as const),
    faker.helpers.arrayElement([202] as const),
    faker.helpers.arrayElement([203] as const),
    faker.helpers.arrayElement([206] as const),
    faker.helpers.arrayElement([207] as const),
    faker.helpers.arrayElement([208] as const),
    faker.helpers.arrayElement([226] as const),
    faker.helpers.arrayElement([300] as const),
    faker.helpers.arrayElement([301] as const),
    faker.helpers.arrayElement([302] as const),
    faker.helpers.arrayElement([303] as const),
    faker.helpers.arrayElement([305] as const),
    faker.helpers.arrayElement([306] as const),
    faker.helpers.arrayElement([307] as const),
    faker.helpers.arrayElement([308] as const),
    faker.helpers.arrayElement([400] as const),
    faker.helpers.arrayElement([401] as const),
    faker.helpers.arrayElement([402] as const),
    faker.helpers.arrayElement([403] as const),
    faker.helpers.arrayElement([404] as const),
    faker.helpers.arrayElement([405] as const),
    faker.helpers.arrayElement([406] as const),
    faker.helpers.arrayElement([407] as const),
    faker.helpers.arrayElement([408] as const),
    faker.helpers.arrayElement([409] as const),
    faker.helpers.arrayElement([410] as const),
    faker.helpers.arrayElement([411] as const),
    faker.helpers.arrayElement([412] as const),
    faker.helpers.arrayElement([413] as const),
    faker.helpers.arrayElement([414] as const),
    faker.helpers.arrayElement([415] as const),
    faker.helpers.arrayElement([416] as const),
    faker.helpers.arrayElement([417] as const),
    faker.helpers.arrayElement([418] as const),
    faker.helpers.arrayElement([421] as const),
    faker.helpers.arrayElement([422] as const),
    faker.helpers.arrayElement([423] as const),
    faker.helpers.arrayElement([424] as const),
    faker.helpers.arrayElement([425] as const),
    faker.helpers.arrayElement([426] as const),
    faker.helpers.arrayElement([428] as const),
    faker.helpers.arrayElement([429] as const),
    faker.helpers.arrayElement([431] as const),
    faker.helpers.arrayElement([451] as const),
    faker.helpers.arrayElement([500] as const),
    faker.helpers.arrayElement([501] as const),
    faker.helpers.arrayElement([502] as const),
    faker.helpers.arrayElement([503] as const),
    faker.helpers.arrayElement([504] as const),
    faker.helpers.arrayElement([505] as const),
    faker.helpers.arrayElement([506] as const),
    faker.helpers.arrayElement([507] as const),
    faker.helpers.arrayElement([508] as const),
    faker.helpers.arrayElement([510] as const),
    faker.helpers.arrayElement([511] as const),
    faker.helpers.arrayElement([-1] as const),
  ]),
  message: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getGetApiHistoryMockHandler = (
  overrideResponse?:
    | GetApiHistory200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<GetApiHistory200Item[]> | GetApiHistory200Item[]),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiHistoryResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getGetApiHistoryMockHandler200 = (
  overrideResponse?:
    | GetApiHistory200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<GetApiHistory200Item[]> | GetApiHistory200Item[]),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiHistoryResponseMock200()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getGetApiHistoryMockHandler500 = (
  overrideResponse?:
    | GetApiHistory500
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiHistory500> | GetApiHistory500),
  options?: RequestHandlerOptions
) => {
  return http.get(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiHistoryResponseMock500()
        ),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiHistoryMockHandler = (
  overrideResponse?:
    | PostApiHistory201
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiHistory201> | PostApiHistory201),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiHistoryResponseMock()
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiHistoryMockHandler201 = (
  overrideResponse?:
    | PostApiHistory201
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiHistory201> | PostApiHistory201),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiHistoryResponseMock201()
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getPostApiHistoryMockHandler500 = (
  overrideResponse?:
    | PostApiHistory500
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiHistory500> | PostApiHistory500),
  options?: RequestHandlerOptions
) => {
  return http.post(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiHistoryResponseMock500()
        ),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getDeleteApiHistoryMockHandler = (
  overrideResponse?:
    | DeleteApiHistory200
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteApiHistory200> | DeleteApiHistory200),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteApiHistoryResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getDeleteApiHistoryMockHandler200 = (
  overrideResponse?:
    | DeleteApiHistory200
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteApiHistory200> | DeleteApiHistory200),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteApiHistoryResponseMock200()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};

export const getDeleteApiHistoryMockHandler500 = (
  overrideResponse?:
    | DeleteApiHistory500
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteApiHistory500> | DeleteApiHistory500),
  options?: RequestHandlerOptions
) => {
  return http.delete(
    '*/api/history',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteApiHistoryResponseMock500()
        ),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
};
export const getEchoAPIMock = () => [
  getGetApiHistoryMockHandler(),
  getPostApiHistoryMockHandler(),
  getDeleteApiHistoryMockHandler(),
];
