name: deploy-sentry

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Install Dependencies
      - name: Install Dependencies
        run: nix develop --command bash -c "pnpm i"
      # Build & Deploy Backend to Cloudflare Workers
      - name: Build & Deploy Backend to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.42.1"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "products/sentry-proxy"
