name: deploy-frontend

permissions:
  contents: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build Check pay-crew
      - name: Build Check pay-crew
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Deploy Frontend to Cloudflare Workers
      - name: Deploy Frontend to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "products/frontend"
