name: deploy-backend

permissions:
  contents: read

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build Check pay-crew
      - name: Build Check pay-crew
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Inject hyperdrive id in ./products/backend/wrangler.toml
      - name: Inject hyperdrive id
        run: |
          sed -i 's/"id": ""/"id": "${{ secrets.CLOUDFLARE_HYPERDRIVE_ID }}"/' ./products/backend/wrangler.jsonc
      # Build & Deploy Backend to Cloudflare Workers
      - name: Build & Deploy Backend to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.38.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "products/backend"
