name: test

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev', 'main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build Check pay-crew
      - name: Build Check pay-crew
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Test pay-crew
      - name: Test pay-crew
        run: nix develop --command bash -c "pnpm run test"
      # ESlint Check
      - name: ESlint Check
        run: nix develop --command bash -c "pnpm run lint"
